//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDrive_v2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class photos
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string yol { get; set; }
        public double boyut { get; set; }
    
        public virtual users users { get; set; }
    }
}
